"""initial

Revision ID: 9f524647c4cd
Revises: 
Create Date: 2026-07-17 10:47:32.630551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f524647c4cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


currency_enum = postgresql.ENUM(
    'RUB',
    name='currency',
    create_type=False,
)

operation_status_enum = postgresql.ENUM(
    'CREATED',
    'PROCESSING',
    'COMPLETED',
    'REJECTED',
    name='operation_status',
    create_type=False,
)

receipt_result_enum = postgresql.ENUM(
    'COMPLETED',
    'REJECTED',
    name='receipt_result',
    create_type=False,
)

receipt_processing_result_enum = postgresql.ENUM(
    'APPLIED',
    'DUPLICATE',
    'IGNORED_CONFLICT',
    name='receipt_processing_result',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    currency_enum.create(bind, checkfirst=True)
    operation_status_enum.create(bind, checkfirst=True)
    receipt_result_enum.create(bind, checkfirst=True)
    receipt_processing_result_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('operation_id', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', currency_enum, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('status', operation_status_enum, server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_amount_gt_0'),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('operation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=120), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', operation_status_enum, nullable=False),
    sa.Column('from_status', operation_status_enum, nullable=True),
    sa.Column('to_status', operation_status_enum, nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('event_id > 0', name='ck_operation_events_event_id_positive'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.operation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'event_id', name='uq_operation_events_operation_id_event_id')
    )
    op.create_table('payment_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name='ck_attempt_count_ge0'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.operation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_payment_dispatches_next_attempt_at'), 'payment_dispatches', ['next_attempt_at'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=120), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=False),
    sa.Column('result', receipt_result_enum, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('provider_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_result', receipt_processing_result_enum, nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.operation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_receipts_operation_id_payload_hash', 'receipts', ['operation_id', 'payload_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipts_operation_id_payload_hash', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_payment_dispatches_next_attempt_at'), table_name='payment_dispatches')
    op.drop_table('payment_dispatches')
    op.drop_table('operation_events')
    op.drop_table('operations')
    # ### end Alembic commands ###

    bind = op.get_bind()
    receipt_processing_result_enum.drop(bind, checkfirst=True)
    receipt_result_enum.drop(bind, checkfirst=True)
    operation_status_enum.drop(bind, checkfirst=True)
    currency_enum.drop(bind, checkfirst=True)
